# Generated by Django 5.2.14 on 2026-07-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_user_options_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('code', models.IntegerField(max_length=6)),
                ('expiration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
