# Generated by Django 5.2.14 on 2026-07-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_adress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='AddAddress',
        ),
    ]
