# Generated by Django 5.2.14 on 2026-07-09 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImages',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kkkk', to='Product.productimages'),
        ),
    ]
