# Generated by Django 5.2.14 on 2026-07-10 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
