# Generated by Django 5.2.14 on 2026-07-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_information_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Information order'),
        ),
    ]
