# Generated by Django 5.2.14 on 2026-07-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_information_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='txte',
            field=models.CharField(max_length=100),
        ),
    ]
