# Generated by Django 5.2.14 on 2026-07-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_information_txte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='txte',
            field=models.CharField(default='Information is up to 80 characters long.', max_length=80),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='colors', to='Product.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='sizes', to='Product.size'),
        ),
    ]
