# Generated by Django 5.2.14 on 2026-07-12 04:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_comment_cartitem_commentlike_productlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='information',
            old_name='txte',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='alt',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='products', to='Product.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='products', to='Product.size'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Primary image'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
