# Generated by Django 5.2.14 on 2026-07-21 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_rename_adress_addaddress'),
        ('Product', '0013_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AlterField(
            model_name='order',
            name='adress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.addaddress'),
        ),
    ]
