# Generated by Django 5.2.14 on 2026-07-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_remove_order_email_remove_order_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adress',
        ),
    ]
