# Generated by Django 5.2.14 on 2026-07-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_remove_order_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.BooleanField(default=0, verbose_name='Price'),
        ),
    ]
