# Generated by Django 5.2.14 on 2026-07-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
    ]
