# Generated by Django 5.2.14 on 2026-07-25 22:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_alter_usdiscount_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usdiscount',
            constraint=models.UniqueConstraint(fields=('user', 'discount'), name='unique_user_discount'),
        ),
    ]
