# Generated by Django 5.2.14 on 2026-07-25 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0022_usdiscount_unique_user_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='product',
        ),
    ]
